#pragma once

#define IDI_ICON_APP 100

#define IDS_SETTINGS 200
#define IDS_EDIT_USER_PHRASES 201
#define IDS_EDIT_EXCLUDED_PHRASES 202
#define IDS_OPEN_USER_DATA_FOLDER 203
#define IDS_OPEN_LOG_FOLDER 204
#define IDS_ENABLE_LOGGING 205
#define IDS_TRACE_LOG 206
#define IDS_RESTART_SERVER 207
#define IDS_TRAY_TIP 208
#define IDS_DAEMON_STARTING 209
#define IDS_SERVER_RUNNING 210

