#pragma once

#define IDI_ICON_APP 100

#define IDS_CONFIG_TITLE 200
#define IDS_RELOAD 201
#define IDS_KEYBOARD_LAYOUT 202
#define IDS_INPUT_MODE 203
#define IDS_CANDIDATE_WINDOW 204
#define IDS_VERTICAL 205
#define IDS_HORIZONTAL 206
#define IDS_CANDIDATE_KEYS 207
#define IDS_CANDIDATES_PER_PAGE 208
#define IDS_SELECTION_CURSOR 209
#define IDS_SELECT_BEFORE 210
#define IDS_SELECT_AFTER 211
#define IDS_MOVE_CURSOR 212
#define IDS_INPUT_BEHAVIOR 213
#define IDS_SHIFT_LETTER_UPPER 214
#define IDS_SHIFT_LETTER_LOWER 215
#define IDS_ESC_CLEAR 216
#define IDS_SHIFT_ENTER 217
#define IDS_CTRL_ENTER 218
#define IDS_CANDIDATES_PUNCTUATION 219
#define IDS_REPEATED_PUNCTUATION 220
#define IDS_CHOOSE_SPACE 221


